export const xlsbookcolumns = [
  { key: "id", header: "Mediennummer" },
  { key: "createdAt", header: "Erzeugt am" },
  { key: "updatedAt", header: "Update am" },
  { key: "rentalStatus", header: "Ausleihstatus" },
  { key: "rentedDate", header: "Ausgeliehen am" },
  { key: "dueDate", header: "Rückgabe am" },
  { key: "renewalCount", header: "Anzahl Verlängerungen" },
  { key: "title", header: "Titel" },
  { key: "subtitle", header: "Untertitel" },
  { key: "author", header: "Autor" },
  { key: "topics", header: "Schlagworte" },
  { key: "imageLink", header: "Bild" },
  { key: "isbn", header: "ISBN" },
  { key: "editionDescription", header: "Edition" },
  { key: "publisherLocation", header: "Verlagsort" },
  { key: "pages", header: "Seiten" },
  { key: "summary", header: "Zusammenfassung" },
  { key: "minPlayers", header: "Min Spieler" },
  { key: "publisherName", header: "Verlag" },
  { key: "otherPhysicalAttributes", header: "Merkmale" },
  { key: "supplierComment", header: "Beschaffung" },
  { key: "publisherDate", header: "Publikationsdatum" },
  { key: "physicalSize", header: "Abmessungen" },
  { key: "minAge", header: "Min Alter" },
  { key: "maxAge", header: "Max Alter" },
  { key: "additionalMaterial", header: "Material" },
  { key: "price", header: "Preis" },
  { key: "externalLinks", header: "Links" },
  { key: "userId", header: "Ausgeliehen von" },
];

export const xlsusercolumns = [
  { key: "createdAt", header: "Erzeugt am" },
  { key: "updatedAt", header: "Update am" },
  { key: "id", header: "Nummer" },
  { key: "lastName", header: "Nachname" },
  { key: "firstName", header: "Vorname" },
  { key: "schoolGrade", header: "Klasse" },
  { key: "schoolTeacherName", header: "Lehrkraft" },
  { key: "active", header: "Freigeschaltet" },
  { key: "eMail", header: "eMail" },
];
